variables:
  BASE_IMAGE: registry.suchgenie.de/icinga-extended
  GIT_SUBMODULE_STRATEGY: recursive

dockerimage:
  stage: build
  image: docker:1.9.1
  script:
    - docker build --pull=true -t $BASE_IMAGE:$CI_BUILD_REF .
    - docker push $BASE_IMAGE:$CI_BUILD_REF
