variables:
  BASE_IMAGE: registry.suchgenie.de/icinga-extended

stages:
  - build
  - tag
  - postHook

build-image:
  stage: build
  script:
    - git submodule init && git submodule update
    - docker build --pull=true -t $BASE_IMAGE:$CI_BUILD_REF .
    - docker push $BASE_IMAGE:$CI_BUILD_REF

tag-build:
  stage: tag
  script:
    - docker pull $BASE_IMAGE:$CI_BUILD_REF
    - if [ "$CI_BUILD_REF_NAME" == "master" ]; then TAG_NAME="latest"; else TAG_NAME="$CI_BUILD_REF_NAME"; fi
    - docker tag -f $BASE_IMAGE:$CI_BUILD_REF $BASE_IMAGE:$TAG_NAME
    - docker push $BASE_IMAGE:$TAG_NAME
