#! /bin/bash

#########THIS part is for Nagios ################################
PROGNAME=`/usr/bin/basename $0`
PROGPATH=`echo $0 | sed -e 's,[\\/][^\\/][^\\/]*$,,'`
REVISION=`echo '$Revision: 1749 $' | sed -e 's/[^0-9.]//g'`
. $PROGPATH/utils.sh

#####################################################################

#Function to print Usage
function usage
{
echo "Usage: $0 -s [apiserver endpoint] -r [not bound warning] -R [not bound critical]"
exit $STATE_UNKNOWN
}

NOT_BOUND_WARN=1
NOT_BOUND_CRIT=2

APISERVER=https://kubernetes.default.svc
#####################################################################
# get parameter values in Variables

while test -n "$1"; do
    case "$1" in
         -h)
            usage
            ;;
         -r)
            NOT_BOUND_WARN=$2
            shift
            ;;
         -R)
            NOT_BOUND_CRIT=$2
            shift
            ;;
         -s)
            APISERVER=$2
            shift
            ;;
         *)
            echo "Unknown argument: $1"
            usage
            ;;
    esac
    shift
done

#####################################################################

TOKEN=$(cat /run/secrets/kubernetes.io/serviceaccount/token)
KUBECTL="kubectl --server $APISERVER --token $TOKEN --certificate-authority=/run/secrets/kubernetes.io/serviceaccount/ca.crt"


STATUS=$( $KUBECTL version 2>&1 )
if [ $? -ne 0 ]; then
        echo "[ERR] failed to connect to apiserver: $STATUS"
        exit $STATE_CRITICAL
fi
if [ "$STATUS" == "" ]; then
        echo "[UNKNOWN] no answer"
        exit $STATE_UNKNOWN
fi

OLD=$( tempfile )
NEW=$( tempfile )
curl --silent --fail 'http://metrics-prometheus-operato-prometheus.metrics.svc:9090/api/v1/query?query=kube_persistentvolumeclaim_status_phase\{job="kube-state-metrics",namespace!~".*ci.*",phase=~"Pending|Unknown|Lost"\}%20offset%205m%20>0' | jq -M -r '.data.result[].metric | "\(.namespace)/\(.pod)"' > ${OLD}
curl --silent --fail 'http://metrics-prometheus-operato-prometheus.metrics.svc:9090/api/v1/query?query=kube_persistentvolumeclaim_status_phase\{job="kube-state-metrics",namespace!~".*ci.*",phase=~"Pending|Unknown|Lost"\}>0' | jq -M -r '.data.result[].metric | "\(.namespace)/\(.pod)"' > ${NEW}
NOT_BOUND=$( cat ${OLD} ${NEW} | sort | uniq -c | awk '{ if ($1 >= 2) print $2 }' )
NOT_BOUND_COUNT=$( echo -n "$NOT_BOUND" | wc -l )
rm ${OLD} ${NEW}
if [ "$NOT_BOUND_COUNT" -ge "$NOT_BOUND_WARN" ]; then
        echo "[WARN] $NOT_BOUND pvs are not bounding: $NOT_BOUND"
        exit $STATE_WARNING
fi
if [ "$NOT_BOUND_COUNT" -ge "$NOT_BOUND_CRIT" ]; then
        echo "[CRIT] $NOT_BOUND pvs are not bounding: $NOT_BOUND"
        exit $STATE_CRITICAL
fi

echo "[OK] all pvs look healthy"
exit $STATE_OK
