apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: client
  namespace: alerting
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: client
    spec:
      hostPID: true
      hostIPC: true
      hostNetwork: true
      containers:
        - name: client
          image: utopiaplanitia/alerting-client:latest
          imagePullPolicy: Never
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          ports:
            - containerPort: 5666
              name: nrpe
          livenessProbe:
            tcpSocket:
              port: 5666
          readinessProbe:
            tcpSocket:
              port: 5666
          volumeMounts:
            - name: dev
              mountPath: /dev
            - name: run
              mountPath: /var/run/docker.sock
            - name: sys
              mountPath: /sys
            - name: log
              mountPath: /var/log
            - name: root
              mountPath: /rootfs
      volumes:
        - name: dev
          hostPath:
              path: /dev
        - name: run
          hostPath:
              path: /var/run/docker.sock
              type: Socket
        - name: sys
          hostPath:
              path: /sys
        - name: log
          hostPath:
              path: /var/log
        - name: root
          hostPath:
              path: /
---
kind: Service
apiVersion: v1
metadata:
  name: client
  namespace: alerting
spec:
  clusterIP: None
  ports:
    - port: 80
  selector:
    app: client