apiVersion: extensions/v1beta1
#apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: client
  namespace: alerting
spec:
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      hostPID: true
      hostIPC: true
      hostNetwork: true
      containers:
        - name: client
          image: ${CLIENT_IMAGE_PULL}
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          ports:
            - containerPort: 5666
              name: nrpe
          livenessProbe:
            tcpSocket:
              port: 5666
          readinessProbe:
            tcpSocket:
              port: 5666
          volumeMounts:
            - name: dev
              mountPath: /dev
            - name: run
              mountPath: /var/run/docker.sock
            - name: sys
              mountPath: /sys
            - name: log
              mountPath: /var/log
            - name: root
              mountPath: /rootfs
      volumes:
        - name: dev
          hostPath:
              path: /dev
        - name: run
          hostPath:
              path: /var/run/docker.sock
              type: Socket
        - name: sys
          hostPath:
              path: /sys
        - name: log
          hostPath:
              path: /var/log
        - name: root
          hostPath:
              path: /